Feature/fehlermeldung ungültiger link
Sybit-Education/Coding-Camp-2018 pull request #35
Opened 2018-08-06 14:09 UTC by GabrielBerchmann

2018-08-06 14:18 UTC, stritti requested changes

2018-08-06 14:18 UTC, stritti commented on src/main/java/edu/sybit/codingcamp/battleship/websocket/WebSocketMappings.java
> +    public void gamefield(Message message) throws MatchNotFoundException, PlayerException {
Da müssen wir noch recherchieren, wie das Exception-Handling bei WebSockets läuft. Die Methode sollte auf jeden Fall keine MAtch... oder PlayerException werfen. Eher eine spezifische WebSocket-Exception für "Internal Error".

Ev. findet sich hier etwas: https://www.devglan.com/spring-boot/spring-boot-websocket-integration-example

2018-08-07 06:07 UTC, GabrielBerchmann commented on src/main/java/edu/sybit/codingcamp/battleship/websocket/WebSocketMappings.java
> +            matchService.addOpponentPlayer(match, player);
Ich benutze hier wieder die addOpponent anstatt die addNewPlayer, die in dem PR neu war. Dann braucht die Methode auch gar keine Exception schmeißen.

2018-08-07 06:30 UTC, stritti approved these changes

2018-08-07 06:41 UTC, merged