Feature/cheat console
Sybit-Education/Coding-Camp-2018 pull request #36
Opened 2018-08-06 14:24 UTC by NeoMC2

Fehler muss bearbeitet werden, aber der cheat fuktioniert

2018-08-06 14:39 UTC, Zelle97 requested changes
Wenn man den Cheat reset benutzt werden die Schiffe des Gegners trotzdem weiter angezeigt.

2018-08-06 14:39 UTC, Zelle97 commented on src/main/javascript/app/main.js
> +            console.log(messageContent);
Die ganzen console logs wieder entfernen.

2018-08-07 08:05 UTC, Zelle97 requested changes
Schiffe werden nach Reset weiterhin angezeigt.

2018-08-07 08:05 UTC, Zelle97 commented on src/main/java/edu/sybit/codingcamp/battleship/service/MatchService.java
> +        timer.schedule(gameOverTask,600000000);
Nicht vergessen den Timer zurückzustellen

2018-08-07 10:56 UTC, GabrielBerchmann approved these changes

2018-08-07 10:56 UTC, GabrielBerchmann commented on src/main/java/edu/sybit/codingcamp/battleship/service/MatchService.java
> +        timer.schedule(gameOverTask,600000000);
sollte man glaub auch wieder zurücksetzen später

2018-08-07 10:57 UTC, merged